function  matlabbatch=MY_get_2_ttest_batch_struct(dest,scans1,scans2,matrix,n1,n2)
   matlabbatch{1}.spm.stats.factorial_design.dir ={dest};
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fsuball.specall.scans = [scans1;scans2];
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fsuball.specall.imatrix = matrix;
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(1).name = 'group';
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(1).dept = 0;
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(1).variance = 1;
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(1).gmsca = 0;
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(1).ancova = 0;
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(2).name = 'subj';
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(2).dept = 0;
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(2).variance = 1;
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(2).gmsca = 0;
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(2).ancova = 0;
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(3).name = 'session';
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(3).dept = 1;
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(3).variance = 0;
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(3).gmsca = 0;
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(3).ancova = 0;
            matlabbatch{1}.spm.stats.factorial_design.des.fblock.maininters{1}.fmain.fnum = 1;%%%
            matlabbatch{1}.spm.stats.factorial_design.cov = struct('c', {}, 'cname', {}, 'iCFI', {}, 'iCC', {});
            matlabbatch{1}.spm.stats.factorial_design.multi_cov = struct('files', {}, 'iCFI', {}, 'iCC', {});
            matlabbatch{1}.spm.stats.factorial_design.masking.tm.tm_none = 1;
            matlabbatch{1}.spm.stats.factorial_design.masking.im = 1;
            matlabbatch{1}.spm.stats.factorial_design.masking.em = {''};
            matlabbatch{1}.spm.stats.factorial_design.globalc.g_omit = 1;
            matlabbatch{1}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = 1;
            matlabbatch{1}.spm.stats.factorial_design.globalm.glonorm = 1;
            matlabbatch{2}.spm.stats.fmri_est.spmmat(1) = cfg_dep('Factorial design specification: SPM.mat File', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
            matlabbatch{2}.spm.stats.fmri_est.write_residuals = 0;
            matlabbatch{2}.spm.stats.fmri_est.method.Classical = 1;
            matlabbatch{3}.spm.stats.con.spmmat(1) = cfg_dep('Model estimation: SPM.mat File', substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
            matlabbatch{3}.spm.stats.con.consess{1}.tcon.name = 'case-ctrl';
             matlabbatch{3}.spm.stats.con.consess{1}.tcon.weights=[1,-1];
%             matlabbatch{3}.spm.stats.con.consess{1}.tcon.weights(1:n1) = 1/n1;
%             matlabbatch{3}.spm.stats.con.consess{1}.tcon.weights(n1+1:n1+n2) = -1/n2;
            matlabbatch{3}.spm.stats.con.consess{1}.tcon.sessrep = 'none';
            matlabbatch{3}.spm.stats.con.delete = 0;
end